services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: $AUTH_POSTGRES_USER
      POSTGRES_PASSWORD: $AUTH_POSTGRES_PASSWORD
      POSTGRES_DB: $AUTH_POSTGRES_DB

    ports:
      - "5432:5432"
    volumes:
      - ./db_data/auth_db/:/var/lib/postgresql/data
    networks:
      - app_network

  auth-service:
    build:
      context: ./auth_service
    container_name: $AUTH_HOST
    depends_on:
      - auth-db
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - .env

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8001:8001"
    depends_on:
      - auth-service
    volumes:
      - ./api-gateway/logs:/app/logs
    env_file:
      - .env
    networks:
      - app_network

  telegram-bot:
    build:
      context: ./telegram-bot
    container_name: telegram-bot
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./telegram-bot/logs:/app/logs

  anime-db:
   image: postgres:15
   container_name: $ANIME_POSTGRES_HOST
   environment:
      POSTGRES_USER: $ANIME_POSTGRES_USER
      POSTGRES_PASSWORD: $ANIME_POSTGRES_PASSWORD
      POSTGRES_DB: $ANIME_POSTGRES_DB
   ports:
     - "$ANIME_POSTGRES_PORT:5432"
   volumes:
     - ./db_data/anime_db/:/var/lib/postgresql/data
   networks:
     - app_network

  anime-service:
   build:
     context: anime-service
   env_file:
     - .env
   depends_on:
     - kafka
     - anime-db
   volumes:
      - ./anime-service/logs:/app/logs
   networks:
     - app_network
   restart: on-failure:5

  zookeeper:
   image: bitnami/zookeeper:latest 
   container_name: zookeeper
   ports:
     - "$ZOOKEEPER_PORT:$ZOOKEEPER_PORT"
   environment:
     ZOOKEEPER_CLIENT_PORT: $ZOOKEEPER_PORT
     ALLOW_ANONYMOUS_LOGIN: yes
   networks:
     - app_network

  kafka:
   image: bitnami/kafka:latest
   container_name: kafka
   depends_on:
     - zookeeper
   ports:
     - "$KAFKA_PORT:$KAFKA_PORT"
   environment:
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:$KAFKA_PORT
     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:$KAFKA_PORT
     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:$ZOOKEEPER_PORT
   networks:
     - app_network

networks:
  app_network:
    driver: bridge
