services:
  auth-db:
    image: postgres:15
    env_file:
      - auth_service/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/auth_db/:/var/lib/postgresql/data
    networks:
      - app_network

  auth-service:
    build:
      context: ./auth_service
    container_name: auth-service
    depends_on:
      - auth-db
    networks:
      - app_network
    env_file:
      - ./auth_service/.env

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - auth-service
    env_file:
      - ./api-gateway/.env
    networks:
      - app_network

#  anime-db:
#    image: postgres:15
#    env_file:
#      - anime-service/.env
#    ports:
#      - "5433:5432"
#    volumes:
#      - ./db_data/anime_db/:/var/lib/postgresql/data
#    networks:
#      - app_network
#
#  anime-service:
#    build:
#      context: anime-service
#    env_file:
#      - anime-service/.env
#    depends_on:
#      - kafka
#      - anime-db
#    networks:
#      - app_network
#
#  zookeeper:
#    image: bitnami/zookeeper:latest  # Новый образ Zookeeper от Bitnami
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ALLOW_ANONYMOUS_LOGIN: yes
#    networks:
#      - app_network
#
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    networks:
#      - app_network

networks:
  app_network:
    driver: bridge
