version: "3.7"

services:
  bot:
    container_name: Telegram-Bot
    env_file:
      - misc/.env
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /App
    depends_on:
      - mongo_db


  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./db-data/mongo/:/data/db





