
# Specify the Redis port
port 6379

# Specify the bind address (use "0.0.0.0" to bind to all interfaces)
bind 0.0.0.0

# Specify the path to the AOF (Append-Only File) for persistence
appendonly yes

# Set a password for Redis (optional)
requirepass sakdh1bhk!uoh123