"""add_models

Revision ID: 19e52ce0f218
Revises: 
Create Date: 2024-12-30 10:21:46.760907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e52ce0f218'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('episodes_aired', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_id'), 'titles', ['id'], unique=False)
    op.create_index(op.f('ix_titles_mal_id'), 'titles', ['mal_id'], unique=False)
    op.create_index(op.f('ix_titles_status'), 'titles', ['status'], unique=False)
    op.create_table('user_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('rewatches', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_rates_id'), 'user_rates', ['id'], unique=False)
    op.create_index(op.f('ix_user_rates_target_type'), 'user_rates', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rates_target_type'), table_name='user_rates')
    op.drop_index(op.f('ix_user_rates_id'), table_name='user_rates')
    op.drop_table('user_rates')
    op.drop_index(op.f('ix_titles_status'), table_name='titles')
    op.drop_index(op.f('ix_titles_mal_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_id'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
