"""update_models

Revision ID: 7da601c6226a
Revises: 19e52ce0f218
Create Date: 2025-04-16 10:57:20.421379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da601c6226a'
down_revision: Union[str, None] = '19e52ce0f218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('titles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user_rates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_rates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_rates', 'updated_at')
    op.drop_column('user_rates', 'created_at')
    op.drop_column('titles', 'updated_at')
    op.drop_column('titles', 'created_at')
    # ### end Alembic commands ###
