MAX_SEARCH_RESPONSE_SIZE = 8
EPISODE_PAGINATION = 30
USER_LIST_PAGINATION = 8
FOLLOW_LIST_PAGINATION = 8


# COMMANDS
SEARCH_CMD = "Поиск 🔍"
MY_LISTS_CMD = "Мои Списки 📔"
TORRENT_CMD = "Торрент(dev) ↕️"
FOLLOW_LIST_CMD = "Мои Подписки ❤️"
