"""update_models

Revision ID: cbedbf647d5b
Revises: 04b81ca555eb
Create Date: 2024-07-13 15:43:38.067067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbedbf647d5b'
down_revision: Union[str, None] = '04b81ca555eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_titles_target_id', table_name='titles')
    op.drop_column('titles', 'target_id')
    op.drop_index('ix_user_rates_user_rate_id', table_name='user_rates')
    op.drop_column('user_rates', 'user_rate_id')
    op.drop_index('ix_users_shiki_id', table_name='users')
    op.drop_column('users', 'shiki_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shiki_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_users_shiki_id', 'users', ['shiki_id'], unique=False)
    op.add_column('user_rates', sa.Column('user_rate_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_user_rates_user_rate_id', 'user_rates', ['user_rate_id'], unique=False)
    op.add_column('titles', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_titles_target_id', 'titles', ['target_id'], unique=False)
    # ### end Alembic commands ###
