"""init_models

Revision ID: 13a651670275
Revises: 
Create Date: 2024-05-23 13:09:02.518273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a651670275'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shiki_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access', sa.String(), nullable=False),
    sa.Column('refresh', sa.String(), nullable=False),
    sa.Column('expire_in', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shiki_credentials_id'), 'shiki_credentials', ['id'], unique=False)
    op.create_table('titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('episodes_aired', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_id'), 'titles', ['id'], unique=False)
    op.create_index(op.f('ix_titles_title_en'), 'titles', ['title_en'], unique=False)
    op.create_index(op.f('ix_titles_title_ru'), 'titles', ['title_ru'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_telegram', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('cred_id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('allow_notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cred_id'], ['shiki_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_id_telegram'), 'users', ['id_telegram'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ru', sa.String(), nullable=False),
    sa.Column('en', sa.String(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_sended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('user_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('rewatches', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_rates_id'), 'user_rates', ['id'], unique=False)
    op.create_index(op.f('ix_user_rates_target_id'), 'user_rates', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_rates_target_type'), 'user_rates', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rates_target_type'), table_name='user_rates')
    op.drop_index(op.f('ix_user_rates_target_id'), table_name='user_rates')
    op.drop_index(op.f('ix_user_rates_id'), table_name='user_rates')
    op.drop_table('user_rates')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id_telegram'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_titles_title_ru'), table_name='titles')
    op.drop_index(op.f('ix_titles_title_en'), table_name='titles')
    op.drop_index(op.f('ix_titles_id'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_shiki_credentials_id'), table_name='shiki_credentials')
    op.drop_table('shiki_credentials')
    # ### end Alembic commands ###
