"""update_models

Revision ID: f424f97037ed
Revises: 13a651670275
Create Date: 2024-05-30 11:45:15.988737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f424f97037ed'
down_revision: Union[str, None] = '13a651670275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shiki_credentials', 'expire_in',
               existing_type=sa.VARCHAR(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.add_column('titles', sa.Column('target_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_titles_target_id'), 'titles', ['target_id'], unique=False)
    op.add_column('user_rates', sa.Column('user_rate_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_rates_user_rate_id'), 'user_rates', ['user_rate_id'], unique=False)
    op.add_column('users', sa.Column('shiki_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('follows', sa.ARRAY(sa.Integer()), nullable=False))
    op.create_index(op.f('ix_users_shiki_id'), 'users', ['shiki_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_shiki_id'), table_name='users')
    op.drop_column('users', 'follows')
    op.drop_column('users', 'shiki_id')
    op.drop_index(op.f('ix_user_rates_user_rate_id'), table_name='user_rates')
    op.drop_column('user_rates', 'user_rate_id')
    op.drop_index(op.f('ix_titles_target_id'), table_name='titles')
    op.drop_column('titles', 'target_id')
    op.alter_column('shiki_credentials', 'expire_in',
               existing_type=sa.DATETIME(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
